sudo: false
language: cpp
os: linux
compiler: gcc

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-7

before_install:
  - wget http://software-dl.ti.com/codegen/esd/cgt_public_sw/PRU/2.2.1/ti_cgt_pru_2.2.1_linux_installer_x86.bin -O clpru.bin
  - chmod +x clpru.bin
  - ./clpru.bin --mode unattended --prefix /opt/ti
    
script: make